### test
GET http://localhost:8008/test

### logChannels
GET http://localhost:8008/log-channels

### getLogs
GET http://localhost:8008/logs



### strikeNews
GET http://localhost:8008/news/strike/bitcoin

### resetNews
GET http://localhost:8008/news/reset/nft

### initializeNews
POST http://localhost:8008/news/initialize
Content-Type: application/json

{
    "name": "nft",
    "regex": "/\\/news\\/nft\\/(\\d+)\\//g",
    "baseUrl": "https://cryptonews.net/news/nft/",
    "discordChannelId": "1196790102093987931"
}