### test
GET http://localhost:8008/test

### logChannels
GET http://localhost:8008/log-channels

### getLogs
GET http://localhost:8008/logs



### strikeNews
GET http://localhost:8008/news/strike/ethereum

### resetNews
GET http://localhost:8008/news/reset/defi

### initializeNews
POST http://localhost:8008/news/initialize
Content-Type: application/json

{
    "name": "ethereum",
    "regex": "/\\/news\\/ethereum\\/(\\d+)\\//g",
    "baseUrl": "https://cryptonews.net/news/ethereum/",
    "discordChannelId": "1196788967517995128"
}


### listSignals
GET http://localhost:8008/signal/list