### test
GET http://localhost:8008/test

### logChannels
GET http://localhost:8008/log-channels

### getLogs
GET http://localhost:8008/logs



### strikeNews
GET http://localhost:8008/news/strike/altcoins

### resetNews
GET http://localhost:8008/news/reset/altcoins

### initializeNews
POST http://localhost:8008/news/initialize
Content-Type: application/json

{
    "name": "altcoins",
    "regex": "/\\/news\\/altcoins\\/(\\d+)\\//g",
    "baseUrl": "https://cryptonews.net/news/altcoins/",
    "discordChannelId": "1196789976831115318"
}


### listSignals
GET http://localhost:8008/signal/list